#! /bin/bash

let words=0
let symbols=0
let spaces=0
while IFS="" read -r line || [ -n "$line" ]
do
   let cnt=`echo -n $line | wc -w`
   let words+=$cnt
   let cnt=${#line}
   let symbols+=$cnt
   res=`tr -dc ' ' <<< $line | wc -c`
   let spaces+=$res
done
echo ""
echo "В тексте $symbols символов, $spaces пробелов и $words слов"
